language: cpp
dist: xenial
env:
matrix:
  fast_finish: true
  include:
    - os: linux
    #- os: osx
    #  osx_image: xcode9
    #  compiler: clang
env:
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"
install:
    # Define the version of miniconda to download
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        MINCONDA_OS=$MINCONDA_LINUX;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        MINCONDA_OS=$MINCONDA_OSX;
      fi
    # Download and install conda
    - wget "http://repo.continuum.io/miniconda/Miniconda3-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export CONDA_PREFIX=$HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
    # Install mamba
    - conda install mamba -c conda-forge
    # Install host dependencies
    - mamba create -n test nlohmann_json google-cloud-cpp cpp-filesystem cpp-half zlib blosc xtl python fsspec numpy numcodecs sh -c conda-forge
    # Install build dependencies
    - mamba install -n test cmake -c conda-forge
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        mamba install -n test gxx_linux-64 libgcc -c conda-forge;
      fi
    # Activate test environment
    - source activate test
    # Install development versions
    - mkdir dev_tmp
    - cd dev_tmp
    # xtensor
    - wget https://github.com/xtensor-stack/xtensor/archive/master.tar.gz -O xtensor.tar.gz -q
    - mkdir xtensor
    - tar zxf xtensor.tar.gz -C xtensor --strip-components 1
    # xtensor-io
    - wget https://github.com/davidbrochart/xtensor-io/archive/chunked_factory.tar.gz -O xtensor-io.tar.gz -q
    - mkdir xtensor-io
    - tar zxf xtensor-io.tar.gz -C xtensor-io --strip-components 1
    # zarrita
    - wget https://github.com/davidbrochart/zarrita/archive/codec.tar.gz -O zarrita.tar.gz -q
    - mkdir zarrita
    - tar zxf zarrita.tar.gz -C zarrita --strip-components 1
    # move to conda environment
    - mv xtensor/include/xtensor $CONDA_PREFIX/include/
    - mv xtensor-io/include/xtensor-io $CONDA_PREFIX/include/
    - mv zarrita/zarrita.py ../test
    - cd ..
    # Build
    - export LDFLAGS="${LDFLAGS} -Wl,-rpath,$CONDA_PREFIX/lib"
    - export LINKFLAGS="${LDFLAGS}"
    - mkdir build
    - cd build
    - cmake -DDOWNLOAD_GTEST=ON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX ..;
    - make -j2 test_xtensor_zarr
    - cd test
script:
    - python ../../test/zarrita_write.py
    - ./test_xtensor_zarr
    - python ../../test/zarrita_read.py
