name: xtensor-zarr
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - nlohmann_json=3.9.1
  - google-cloud-cpp=1.20.0
  - aws-sdk-cpp=1.8.151
  - cpp-filesystem=1.3.8
  - zlib=1.2.11
  - blosc=1.21.0
  - xtensor=0.23.8
  - xtensor-io=0.12.7
  - zarray=0.1.0
  - gdal=3.0.4
  # Test dependencies
  - fsspec
  - numpy
  - numcodecs
  - zarr

