name: xtensor-zarr
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - nlohmann_json
  - google-cloud-cpp=1.20.0
  - aws-sdk-cpp
  - cpp-filesystem
  - zlib
  - xtensor=0.23.8
  - xtensor-io=0.12.7
  - zarray=0.1.0
  - gdal=3.0.4
  # Test dependencies
  - fsspec
  - numpy
  - numcodecs
  - zarr

