name: xtensor-zarr
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - nlohmann_json
  - google-cloud-cpp=1.20.0
  - aws-sdk-cpp
  - cpp-filesystem
  - zlib
  - xtensor-io=0.12.4
  - gdal
  - zarray=0.0.5
  # Test dependencies
  - fsspec
  - numpy
  - numcodecs
  - zarr

