name: xtensor-zarr
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  # Host dependencies
  - nlohmann_json
  - google-cloud-cpp
  - aws-sdk-cpp
  - cpp-filesystem
  - zlib
  - xtensor-io
  - zarray
  # Test dependencies
  - fsspec
  - numpy
  - numcodecs
  - zarr

