name: xtensor-zarr
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=3
  - xeus-cling=0.12.0
  - xwidgets=0.25.0
  - jupyterlab_widgets=1.0.0
  - ffmpeg=4.3.1  # openimageio is being added as a runtime requirement to xtensor-io
  - widgetsnbextension
  - xtensor-zarr=0.0.7=*_1
  - cppcolormap=1.3.0
  - bash_kernel
  - google-cloud-cpp=1.20.0
  - allthekernels
  - fsspec
  - numcodecs
  - numpy
  - matplotlib
  - zarr
